import Head from 'next/head'
import Image from 'next/image'
import Grid from '../components/content/Grid'


export default function Home(props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=''>
        <Grid characters = {props.data}/>
      </div>

    </div>
  )
}


export async function getStaticProps(){
  const res = await fetch("https://www.breakingbadapi.com/api/characters?category=Breaking+Bad");
  const data = await res.json();

  return{
    props:{
      data:data
    }
  }
}